package me.xihuxiaolong.generalcomponent.common.database.localentity;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import me.xihuxiaolong.generalcomponent.common.database.localentity.DBCache;
import me.xihuxiaolong.generalcomponent.common.database.localentity.DBShortNote;

import me.xihuxiaolong.generalcomponent.common.database.localentity.DBCacheDao;
import me.xihuxiaolong.generalcomponent.common.database.localentity.DBShortNoteDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dBCacheDaoConfig;
    private final DaoConfig dBShortNoteDaoConfig;

    private final DBCacheDao dBCacheDao;
    private final DBShortNoteDao dBShortNoteDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dBCacheDaoConfig = daoConfigMap.get(DBCacheDao.class).clone();
        dBCacheDaoConfig.initIdentityScope(type);

        dBShortNoteDaoConfig = daoConfigMap.get(DBShortNoteDao.class).clone();
        dBShortNoteDaoConfig.initIdentityScope(type);

        dBCacheDao = new DBCacheDao(dBCacheDaoConfig, this);
        dBShortNoteDao = new DBShortNoteDao(dBShortNoteDaoConfig, this);

        registerDao(DBCache.class, dBCacheDao);
        registerDao(DBShortNote.class, dBShortNoteDao);
    }
    
    public void clear() {
        dBCacheDaoConfig.getIdentityScope().clear();
        dBShortNoteDaoConfig.getIdentityScope().clear();
    }

    public DBCacheDao getDBCacheDao() {
        return dBCacheDao;
    }

    public DBShortNoteDao getDBShortNoteDao() {
        return dBShortNoteDao;
    }

}
